FROM maven:3.0-eclipse-temurin-21 AS build

WORKDIR /app

COPY pom.xml ./

## dependency:go-offline é utilizado para deixar tudo PRE-BAIXADO. Isso significa que caso haja alteração no codigo, não sera necessario uma instalação do zero novamente, ele baixara apenas DEPS necessario.

RUN --mount=type=cache,target=/root/.m2 \ 
    mvn -q -B -DskipTests dependency:go-offline

COPY src ./src

RUN --mount=type=cache,target=/root/.m2 \
    mvn -q -B -DskipTests clean package

RUN bash -lc 'cp target/*.jar target/app.jar'