name: CD - Docker (GHCR)

on:
  push:
    branches: [ dev, main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Baixando o codigo
        uses: actions/checkout@v4

      - name: Aplicando lowercase em IMAGE_NAME
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: configurando o Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construindo e publicando a imagem
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile
          push: true
          tags: |
           ghcr.io/ferrari65/backend-gestao_acesso:sha-${{ github.sha }}
           ghcr.io/ferrari65/backend-gestao_acesso:${{ github.ref_name }}
